### ISSUE TITLE
streaming open issues

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1055]
- [x] streaming pipeline running jobs should be displayed separately so that it can be reached if other 100 regular pipelines were executed
- [ ] do we support Pause\Resume on streaming and what does it means do we stop the stateful and the stateless or just the stateless. if not supported the option should be removed from UI
- [x] "Run node' option should be removed from UI
- [x] Debugging streaming pipeline
- [x] what are the statistics we  want to display during the run - do we want to save them and where
- [ ] add metrics to prometheus

**Comment by NassiHarel** [comment]
- [ ] streaming pipeline running jobs should be displayed separately so that it can be reached if other 100 regular pipelines was executed
*Nassi*: I think there should be a filter/icons/search for that, it should display regardless of the 100 pipelines.

- [ ] do we support Pause\Resume on streaming and what does it means do we stop the stateful and the stateless or just the stateless. if not supported the option should be removed from UI.
*Nassi*: I think we can implement it at the algorithm level.

- [ ] "Run node' option should be removed from UI
*Nassi*: agree.

- [ ] pipeline ttl we should add the option to set to infinity currently the default is 1 hour
*Nassi*: I think that users should decide, but we need to allow 0/-1 for infinity.

- [ ] Debugging streaming pipeline
*Nassi*: 

- [ ] stateless node failover due to algorithm rasing error does stop the entire job?
*Nassi*: for now it acts like the batch (with tolerance).

- [ ] what are the statistics we want to display during the run - do we want to save them and where.
*Nassi*: the statistics are saved and override at any given time.

### Additions:
- [ ] we need to save samples of the streaming data.

**Comment by tamir321** [comment]
- [ ] stateless node failover due to algorithm rasing error does stop the entire job?
Nassi: for now it acts like the batch (with tolerance).
Tamir: after consulting with Maty: the streaming pipelines should not stop due to an algorithm error
