### ISSUE TITLE
graph data should be saved in mongo not redis

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1199]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
graph data should be saved in mongo not redis
if restarting the cluster the graph data is lost

**Comment by yehiyam** [comment]
fixed by 
https://github.com/kube-HPC/DAG.hkube/pull/19
https://github.com/kube-HPC/monitor-server/pull/37
https://github.com/kube-HPC/hkube/pull/1198
https://github.com/kube-HPC/db.hkube/pull/10

Notes:
1. api-server should migrate graphs from redis to mongo
2. new graphs are written to redis
3. monitor-server reads graphs as part of the `job`

Affected functionality:
1. graph view in UI
2. get graph api (raw, parsed)
3. tensor boards
4. pipeline driver recovery

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.0.121",
fullSystemVersion: "v2.0.121-1617274600478",
versions: [
