### ISSUE TITLE
Insufficient resources. - warn if task is not starting due to resource plus give numbers

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1638]
Insufficient resources. - warn if task is not starting due to resource plus give numbers
show in the context of the task in the graph

**Comment by RonShvarz** [comment]
New approach - 
Task executor - make a similar appserver for REST_API requests as in pipeline-driver-queue,
Make a local DB for task executor to hold algo states of resources,
add api-server call with the graph request

**Comment by RonShvarz** [comment]
![image](https://user-images.githubusercontent.com/34660076/236675030-cb75890e-9e34-4e4f-8ef4-eaa060c81404.png)
Currently - similar logs are already being monitored under unScheduledAlgorithms and written to etcd

**Comment by RonShvarz** [comment]
- [ ] Add ann needed info to etcd under task-executor discovery

- [ ] Build warning message under queryJob under api-server

**Comment by RonShvarz** [comment]
Message is located in graph(object).node.warnings

**Comment by zivglik** [comment]
"nodes":[1 item
0:{18 items
"nodeName":"testnoselector"
"algorithmName":"testnoselector"
"algorithmVersion":"935fepmvl7"
"taskId":"0cjx2ea2"
"podName":NULL
"status":"FailedScheduling"
"startTime":NULL
"endTime":NULL
"level":0
"error":NULL
"warnings":[1 item
0:"Summary: No nodes available for scheduling due to selector condition - 'type=cpu-extreme' All 3 nodes unmatched due to selector - type=cpu-extreme"
]
"retries":NULL

**Comment by golanha** [comment]
@RonShvarz The node selector anayze should not be part of the message summery in case it is not  the problem itself

**Comment by RonShvarz** [comment]
> @RonShvarz The node selector anayze should not be part of the message summery in case it is not the problem itself

Opened #1738

**Comment by RonShvarz** [comment]
> @RonShvarz The node selector anayze should not be part of the message summery in case it is not the problem itself

Opened #1738
