### ISSUE TITLE
Changing attributes or image of an algorithm should restart any of the algorithm pod where worker is in ready state.  

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#319]

**Comment by amiryi365** [comment]
This is a **Bug**, not Enhancement, because the behavior is clearly **not** the expected one.
It causes a user who doesn't know that to wonder why his/her new fix doesn't make any change.
It enforce a user who already knows that to wait until Pod is down to run again the pipeline.
**Please fix it!**
